// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"github.com/Duke1616/etools/job/schedule"
	"github.com/Duke1616/etools/job/service"
	"github.com/Duke1616/etools/job/storage"
	"github.com/Duke1616/etools/job/storage/mysql"
)

// Injectors from wire.go:

func InitServer() *schedule.Scheduler {
	db := InitDB()
	gormStoragerCronJob := mysql.NewGormJob(db)
	storager := storage.NewStorage(gormStoragerCronJob)
	serviceService := service.NewService(storager)
	scheduler := schedule.NewScheduler(serviceService)
	return scheduler
}
